'use strict';

const domainMaps = {
    'hotmail.com': 'hotmail',
    'bing.com': 'hotmail',
    'live.com': 'hotmail',
    'msn.com': 'hotmail',
    'microsoft.com': 'hotmail',
    'outlook.com': 'hotmail',
    'windowsphone.com': 'hotmail',
    'bing.net': 'hotmail',
    'msn.net': 'hotmail',
    'live.net': 'hotmail',
    'hotmail.net': 'hotmail',
    'outlook.net': 'hotmail',
    'windowsphone.net': 'hotmail',
    'bing.eu': 'hotmail',
    'msn.eu': 'hotmail',
    'live.eu': 'hotmail',
    'hotmail.eu': 'hotmail',
    'outlook.eu': 'hotmail',
    'bing.co': 'hotmail',
    'msn.co': 'hotmail',
    'live.co': 'hotmail',
    'hotmail.co': 'hotmail',
    'outlook.co': 'hotmail',
    'bing.eu': 'hotmail',
    'msn.eu': 'hotmail',
    'live.eu': 'hotmail',
    'hotmail.eu': 'hotmail',
    'outlook.eu': 'hotmail',
    'hotmail.es': 'hotmail',
    'hotmail.com.ar': 'hotmail',
    'hotmail.fr': 'hotmail',
    'hotmail.it': 'hotmail',
    'hotmail.co.uk': 'hotmail',
    'hotmail.dk': 'hotmail',
    'hotmail.nl': 'hotmail',
    'hotmail.au': 'hotmail',
    'gmail.com': 'gmail',
    'googlemail.com': 'gmail',
    'google.com': 'gmail'
};

module.exports = domainMaps;